package FootballLeague;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import FootballLeague.FootballLeagueFrontend.MainGame;
import FootballLeague.FootballLeagueFrontend.MainMenu;
import javafx.application.Application;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        Application.launch(MainGame.class, null);


    }
}
